#Hugo configuration
title = "test 2"
baseURL = "https:\/\/www.test2asdf.com"
languageCode = "en-us"
theme = "tvpage"
disablePathToLower = "true"
enableRobotsTXT = true

[params]
loginId = "1758403"
subfolder = ""
